---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mariadb:11
        name: mysql
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector: 
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mysql-network-policy
spec:
  podSelector:
    matchLabels:
      app: mysql
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: drupal
    ports:
    - protocol: TCP
      port: 3306

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: drupal
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: drupal
    spec:
      initContainers:
      - name: init-drupal
        image: drupal-local
        command: ["/bin/sh", "-c"]
        args:
        - '[ -z "$(ls -A /var/www/html-target)" ] && cp -a /var/www/html/. /var/www/html-target/ || echo "Target not empty, skipping copy"'
        volumeMounts:
        - name: drupal-persistent-storage
          mountPath: /var/www/html-target
      containers:
      - image: drupal-local
        name: drupal
        env:
        - name: DRUPAL_DATABASE_HOST
          value: mysql
        - name: DRUPAL_DATABASE_PORT_NUMBER
          value: "3306"
        - name: DRUPAL_DATABASE_NAME
          value: drupal
        - name: DRUPAL_DATABASE_USER
          value: root
        - name: DRUPAL_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        ports:
        - containerPort: 80
        volumeMounts:
        - name: drupal-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: drupal-persistent-storage
        persistentVolumeClaim:
          claimName: drupal-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: drupal
spec:
  selector: 
    app: drupal
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer